#steps:
#  - name: gradle:jdk17
#    entrypoint: gradle
#    args: [ 'build' ]
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2', '.' ]
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'push', 'us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2' ]
#images: [ 'us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2' ]

steps:
  - name: gradle:jdk17
    entrypoint: gradle
    args: [ 'build' ]
    id: Build Project
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '--no-cache', '-t', 'us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2:$COMMIT_SHA', '.', '-f', 'Dockerfile' ]
    id: Build Image
  - name: gcr.io/cloud-builders/docker
    args: [ 'push', 'us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2:$COMMIT_SHA' ]
    id: Push Image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: [ 'run', 'services', 'update', 'valhallabot2', '--platform=managed', '--image=us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2:$COMMIT_SHA', '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=d7160db1-c11a-4715-9478-4d781b213aa6', '--region=us-central1', '--quiet' ]
    id: Deploy Image
    entrypoint: gcloud

images:
  - 'us-docker.pkg.dev/vernal-union-355622/gcr.io/valhallabot2:$COMMIT_SHA'
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - valhallabot2
